# Generated by Django 4.1.7 on 2023-05-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlantName', models.CharField(default='', max_length=20)),
                ('PlantSname', models.CharField(default='', max_length=20)),
                ('PlantPrice', models.IntegerField(default='', max_length=6)),
                ('PlantProperties', models.TextField(default='')),
                ('PlantImg', models.TextField(default='')),
                ('PlantInitialQuantity', models.IntegerField(default=1, max_length=5)),
                ('PlantQuantity', models.IntegerField(default=1, max_length=5)),
                ('PlantAddCart', models.IntegerField(default='Add', max_length=10)),
            ],
        ),
    ]
