# Generated by Django 4.1.7 on 2023-05-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='plantType',
            field=models.CharField(default='', max_length=20),
        ),
    ]
