# Generated by Django 4.1.7 on 2023-05-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantDatabase', '0002_details_planttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='plantType',
            new_name='PlantType',
        ),
    ]
