# Generated by Django 4.1.7 on 2023-05-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantDatabase', '0003_rename_planttype_details_planttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='PlantAddCart',
            field=models.CharField(default='Add', max_length=10),
        ),
    ]
