# Generated by Django 4.1.7 on 2023-05-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantDatabase', '0004_alter_details_plantaddcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='PlantAddCart',
            new_name='Add_to_cart',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='PlantImg',
            new_name='Img_path',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='PlantInitialQuantity',
            new_name='Initial_quantity',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='PlantName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='PlantPrice',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='PlantProperties',
            new_name='Properties',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='PlantQuantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='PlantSname',
            new_name='Scientific_Name',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='PlantType',
            new_name='type',
        ),
    ]
