# Generated by Django 4.0 on 2023-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantDatabase', '0005_rename_plantaddcart_details_add_to_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='hidden',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='details',
            name='Initial_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='details',
            name='Price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='details',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='details',
            name='Scientific_Name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
